services:
  chanchito:
    build:
      context: .
      dockerfile : Dockerfile.dev
    ports:
      - "3000:3000"
    links: 
      - monguito
    volumes:
      - .:/home/app
#Docker compose crea una red 
  monguito:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nico
      - MONGO_INITDB_ROOT_PASSWORD=password 
    volumes:
      - mongo-data: /data/db
      #rutas mysql -> /var/lib/mysql
      #rutas postgres -> /var/lib/postgresql/data 
version:
  mongo-data:

# Correr el archivo: docker compose -f docker-compose-dev.yml up 
