services:
  bd_mysql:
    image: mysql:8.0
    container_name: mi-servidor-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secreto
      MYSQL_DATABASE: base_de_datos
      MYSQL_USER: admin
      MYSQL_PASSWORD: micontraseñasegura
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: